# https://github.com/helix-editor/helix/blob/master/languages.toml

[language-server.harper-ls]
command = "harper-ls"
args = ["--stdio"]

[language-server.harper-ls.config.harper-ls.linters]
AvoidCurses = false
BoringWords = true
ToDoHyphen = false

[[language]]
name = "markdown"
soft-wrap.enable = true
language-servers = [ "marksman", "markdown-oxide", "harper-ls" ]

[[language]]
name = "rust"
language-servers = [ "rust-analyzer", "harper-ls" ]
